In [74]:
!pwd

/Users/sentissi/code/Merarztin/Waves_of_The_Heart


In [126]:
import os
import pandas as pd

# Path of the folder containing CSV files
folder_path = '/Users/sentissi/code/Merarztin/Waves_of_The_Heart'

# Create a list of the filenames of the CSV files to merge
file_list = [
    'final_dataframe_from_a.csv',
    'final_dataframe_from_b.csv',
    'final_dataframe_from_c.csv',
    'final_dataframe_from_d.csv',
    'final_dataframe_from_e.csv',
    'final_dataframe_from_f.csv'
    
]

# Create an empty list to store the dataframes
df_list = []

# Loop through each CSV file in the file_list, read it into a dataframe, and append to df_list
for file in file_list:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)
    df_list.append(df)

# Concatenate all the dataframes in df_list into a single dataframe
audio_data = pd.concat(df_list, ignore_index=True)

# Write the merged dataframe to a CSV file
audio_data.to_csv('/Users/sentissi/code/Merarztin/Waves_of_The_Heart/merged_file.csv', index=False)
audio_data = audio_data.drop('Unnamed: 0', axis=1)
audio_data = audio_data.drop('wav_file', axis=1)


# uncomment to save audio_data
#audio_data.to_csv('audio_data.csv', index=True)

In [117]:
from sklearn.preprocessing import StandardScaler

X = audio_data.drop('label', axis=1)
y = audio_data['label']

# Initialize the scaler object
scaler = StandardScaler()

# Normalize the data
X_normalized = scaler.fit_transform(X)

# Convert the numpy array back to a Pandas dataframe (if needed)
X = pd.DataFrame(X_normalized, columns=X.columns)
X.head()

Decomp0_Duration  Decomp0_Energy  Decomp0_Peak Amplitude  \
0         -0.495519        1.988746                1.520042   
1         -0.148776       -0.484407               -1.967521   
2          1.083047       -0.099754                0.263997   
3          1.060607       -0.479304               -1.537421   
4         -0.148776       -0.467346               -1.892627   

   Decomp0_Mean Amplitude  Decomp0_Std Amplitude  Decomp0_Skew Amplitude  \
0                1.587052               3.519293               -0.836662   
1               -0.957998              -1.510138               -0.440362   
2               -0.350288              -0.183049               -0.852198   
3               -0.914547              -1.417831               -0.508506   
4               -0.774353              -1.239665               -0.836177   

   Decomp0_Kurtosis Amplitude  Decomp1_Duration  Decomp1_Energy  \
0                   -0.382522         -0.495519        1.101405   
1                    1.037689         -0.148776       -0.108832   
2                   -0.117095          1.083047       -0.105456   
3                    1.511734          1.060607        0.069316   
4                   -0.382370         -0.148776       -0.109003   

   Decomp1_Peak Amplitude  ...  Decomp3_Std Amplitude  Decomp3_Skew Amplitude  \
0                5.037063  ...               3.630133               -0.799979   
1               -0.505122  ...              -0.645917               -0.801656   
2               -0.318330  ...              -0.340923                0.944944   
3                6.960647  ...               0.762387               -0.801451   
4               -0.515888  ...              -0.648296               -0.798749   

   Decomp3_Kurtosis Amplitude  Decomp4_Duration  Decomp4_Energy  \
0                   -0.649064         -0.495516        1.335286   
1                   -0.654480         -0.148758       -0.165190   
2                    1.567820          1.083066       -0.157835   
3                   -0.479740          1.060582       -0.049528   
4                   -0.603471         -0.148758       -0.165321   

   Decomp4_Peak Amplitude  Decomp4_Mean Amplitude  Decomp4_Std Amplitude  \
0                3.177899                1.027847               3.666648   
1               -0.494659               -0.332482              -0.549334   
2               -0.205753               -0.332719              -0.384611   
3               -0.243619               -0.217973               0.217508   
4               -0.480032               -0.361807              -0.551666   

   Decomp4_Skew Amplitude  Decomp4_Kurtosis Amplitude  
0                0.043408                    0.001250  
1               -0.825223                   -0.749078  
2                1.516972                    1.394032  
3               -0.825181                   -0.686848  
4               -0.740903                   -0.721545  

[5 rows x 35 columns]

# Logistic regression

In [118]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

#Spliting the data stored in training-a
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the logistic regression model
logistic_regression = LogisticRegression(max_iter=1000, C=1.5601864044243652)

# Perform cross-validation
scoring = ['accuracy', 'precision', 'recall', 'f1']
cv_results = cross_validate(logistic_regression, X_train, y_train, cv=10, scoring=scoring)

# Compute the performance metrics
accuracy = cv_results['test_accuracy'].mean()
precision = cv_results['test_precision'].mean()
recall = cv_results['test_recall'].mean()
f1 = cv_results['test_f1'].mean()

# Print the performance metrics
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1-score: ", f1)

Accuracy:  0.6647401247401248
Precision:  0.62366713022258
Recall:  0.3587070471753057
F1-score:  0.4546453676568353


# KNN model

In [119]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Perform cross-validation
scoring = ['accuracy', 'precision', 'recall', 'f1']
cv_results = cross_validate(knn, X_train, y_train, cv=10, scoring=scoring)

# Create a KNN classifier object
knn = KNeighborsClassifier(n_neighbors=5)

# Fit the classifier to the training data
knn.fit(X_train, y_train)

# Use the trained classifier to make predictions on the testing data
y_pred = knn.predict(X_test)

# Evaluate the performance of the classifier
#What is the ratio of correct predictions for this model
accuracy = accuracy_score(y_test, y_pred)
# When the model signals an at-risk heartbeat, how often is it correct?
precision = precision_score(y_test, y_pred, average='weighted')
#What percentage of at-risk heartbeats is the model able to flag
recall = recall_score(y_test, y_pred, average='weighted')
#What is the model's ability to flag as many at-risk heartbeats as possible while limiting false alarms
f1 = f1_score(y_test, y_pred, average='weighted')

print("Accuracy: ", accuracy)
print("Recall: ", recall)
print("Precision: ", precision)
print("F1-score: ", f1)

Accuracy:  0.6172839506172839
Recall:  0.6172839506172839
Precision:  0.6125285779606767
F1-score:  0.6139126078672209


# SVM

## Linear SVM

In [120]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize SVM classifier
SVC = SVC(kernel='linear', C = 10)

# Perform cross-validation
scoring = ['accuracy', 'precision', 'recall', 'f1']
cv_results = cross_validate(SVC, X_train, y_train, cv=10, scoring=scoring)

# Fit classifier to training data
SVC.fit(X_train, y_train)

# Make predictions on test data
y_pred = SVC.predict(X_test)

# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')

# Print evaluation metrics
print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)
print('F1 score:', f1)

Accuracy: 0.6435185185185185
Precision: 0.6413895993179881
Recall: 0.597605712548185
F1 score: 0.5862949563736966


## Kernel SVM

In [121]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize SVM classifier
SVC = SVC(kernel='rbf', C = 10)

# Perform cross-validation
scoring = ['accuracy', 'precision', 'recall', 'f1']
cv_results = cross_validate(SVC, X_train, y_train, cv=10, scoring=scoring)

# Fit classifier to training data
SVC.fit(X_train, y_train)

# Make predictions on test data
y_pred = SVC.predict(X_test)

# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')

# Print evaluation metrics
print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)
print('F1 score:', f1)

Accuracy: 0.6574074074074074
Precision: 0.6452147508206187
Recall: 0.6332159566850741
F1 score: 0.634567901234568


# Decision Tree

In [122]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Perform cross-validation
scoring = ['accuracy', 'precision', 'recall', 'f1']
cv_results = cross_validate(SVC, X_train, y_train, cv=10, scoring=scoring)

# Initialize the decision tree classifier
decision_tree = DecisionTreeClassifier(max_depth=2)

# Fit the classifier to the training data
decision_tree.fit(X_train, y_train)

# Use the trained classifier to make predictions on the testing data
y_pred = decision_tree.predict(X_test)

# Evaluate the performance of the classifier
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

# Print the performance metrics
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1-score: ", f1)

Accuracy:  0.6342592592592593
Precision:  0.6272147093992888
Recall:  0.6342592592592593
F1-score:  0.6270384786379799


# Confusrion matrix

In [123]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

# Initialize the models
logistic_regression = LogisticRegression(max_iter=1000, C=1.5601864044243652)
knn = KNeighborsClassifier(n_neighbors=5)
svm_linear = SVC(kernel='linear', C=0.01)
svm_rbf = SVC(kernel='rbf', C=10, gamma=0.001)

# Train the models on the training data
logistic_regression.fit(X_train, y_train)
knn.fit(X_train, y_train)
svm_linear.fit(X_train, y_train)
svm_rbf.fit(X_train, y_train)
decision_tree.fit(X_train, y_train)

# Use the trained models to make predictions on the testing data
y_pred_lr = logistic_regression.predict(X_test)
y_pred_knn = knn.predict(X_test)
y_pred_svm_linear = svm_linear.predict(X_test)
y_pred_svm_rbf = svm_rbf.predict(X_test)
y_pred_svm_dec_tree = decision_tree.predict(X_test)

# Compute the confusion matrices
cm_lr = confusion_matrix(y_test, y_pred_lr)
cm_knn = confusion_matrix(y_test, y_pred_knn)
cm_svm_linear = confusion_matrix(y_test, y_pred_svm_linear)
cm_svm_rbf = confusion_matrix(y_test, y_pred_svm_rbf)
cm_svm_dec_tree = confusion_matrix(y_test, y_pred_svm_dec_tree)

# Print the confusion matrices
print("Logistic Regression confusion matrix:")
print(cm_lr)
print("\nKNN confusion matrix:")
print(cm_knn)
print("\nSVM with linear kernel confusion matrix:")
print(cm_svm_linear)
print("\nSVM with RBF kernel confusion matrix:")
print(cm_svm_rbf)
print("\nDecision Tree confusion matrix:")
print(cm_svm_dec_tree)

Logistic Regression confusion matrix:
[[314  65]
 [177  92]]

KNN confusion matrix:
[[268 111]
 [137 132]]

SVM with linear kernel confusion matrix:
[[341  38]
 [210  59]]

SVM with RBF kernel confusion matrix:
[[333  46]
 [196  73]]

Decision Tree confusion matrix:
[[285  94]
 [143 126]]
